spring.application.name=Porter Backend
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/porter}
spring.datasource.username=${DB_USERNAME:porter}
spring.datasource.password=${DB_PASSWORD:porter}
spring.flyway.enabled=true
